### ISSUE TITLE
Export-SnipeItCredentials Documentation

### ISSUE THREAD

**Issue by blighter** [mattcarras/SnipeItSyncPS#6]
It is mentioned about using Export-SnipeItCredentials function, but not where we can get this function from?

**Comment by mattcarras** [comment]
Hi @blighter,

Sorry I'm a bit late responding! Export-SnipeItCredentials is the first function contained in SnipeIt-Sync-PS.ps1, as mentioned under [Main Functions in SnipeIt-Sync-PS.ps1](https://github.com/mattcarras/SnipeItSyncPS#main-functions-in-snipeit-sync-psps1) in the Readme. You'll have to source the script before you're able to use any of the functions, like so:

`. .\SnipeIt-Sync-PS.ps1`

All functions have documented help. Example (after dot sourcing SnipeIt-Sync-PS1.ps1):

`Export-SnipeItCredentials -?`
